Flip coin works
78carla/casino-dapp-blockend pull request #8
Opened 2023-04-03 16:30 UTC by 78carla

- Deleted 1000 token minting on the CasinoToken.sol
- Minted 1000 tokens (depositToken() function) on Casino.sol. Used the DeploymentCasino.ts. This is the prizePool - necessary for paying the wins).
- Added the approve() token
- Adjusted the transferFrom()
- Added the coin result on the flipCoin

2023-04-03 19:52 UTC, 6124437 requested changes

2023-04-03 19:52 UTC, arjanjohan commented on contracts/Casino.sol
> +    //Mint some T7E tokens for the contract - it is the initial prizePool
This function can now be called by everyone, this should be onlyOwner if we use this. 
But I believe we should not fund the casino like this, because these tokens will not be backed by any ETH. So if the casino is at a loss, and gamblers want to withdraw, there would not be enough ETH. For testing purposes it if fine to do this. But in the end we should not create coins from thin air. Only fund the casino by selling T7E (using real fake ETH). 
So IMO, we should for testing put back in place the minting bit in casino.ts script. And when we deliver our working project we remove the minting function as well. The casino owner (deployer) should just buy T7E right afer deployment to fund the casino.

2023-04-03 19:52 UTC, arjanjohan commented on contracts/Casino.sol
> +        paymentToken.approve(address(this), maxValue);
I removed that approve earlier, because it's not needed for the transfer on line 72. This transferFrom requires an approval from the gambler, who makes the approval in the casino.ts script on line 111-118.
From within the casino.sol, we cannot make approvals in name of the gambler, only in name of the casino contract. Otherwise it would be super dangerous to interact with this contract, which approves all kind of things on your behalf.

When you mentioned that winning bets cannot be payed out in the contract where I removed the approval, I think I finally understand what is going on.
This does not approves for the transferFrom(), but for the transfer() in line 80. 

So I think we should move the approval to line 79, and we can assign it a value playPrice * 2.

edit: I do recall the matheus mention we should round up the approval value to account for the gas costs for the transaction as well. So probably we should do playPrice * 2 + some value. Or for now just use playprice*3 for the approval and see if it works. we can optimize later

2023-04-03 19:52 UTC, arjanjohan commented on contracts/Casino.sol
>      function getRandomNumber() public view returns (bool) {
we can change the function name, as it does not return a random number.
Or even better: make this function return a random number. This way we can reuse the getRandomNumber for other games (dice game for example).  Then in flipCoin we can put something like:
this.getRandomNumber % 2 == 0 ? false: true
or
this.getRandomNumber % 2 == 0 ? "heads" : "tails"

2023-04-03 19:52 UTC, arjanjohan commented on contracts/Casino.sol
>              paymentToken.transfer(msg.sender, playPrice * 2);
The value 2 should be moved to a state variable, since it's more organized this way and we use it more than once. 
Also we should lower it, so there is a profit for the casino. 1.9 would be good IMO

2023-04-03 19:52 UTC, arjanjohan commented on contracts/Casino.sol
> +    string public coin;
this is the result of the coinflip I think? There is no need to store this in memory right?

2023-04-04 10:31 UTC, 78carla commented on contracts/Casino.sol
> +    //Mint some T7E tokens for the contract - it is the initial prizePool
Agree with you, but without the premint it didn't work the payment of the win. If it works without this we can remove it.

2023-04-04 10:37 UTC, 78carla commented on contracts/Casino.sol
> +        paymentToken.approve(address(this), maxValue);
- It makes sense to have the user approve the script and move this to line 80.
- At the moment I think we are fine to have playprice*3. Having numbers with decimals created me some issues at the beginning. At think can be a future implementation.

2023-04-04 10:38 UTC, 78carla commented on contracts/Casino.sol
>      function getRandomNumber() public view returns (bool) {
Ok, agree. +1 the proposed change.

2023-04-04 10:39 UTC, 78carla commented on contracts/Casino.sol
>              paymentToken.transfer(msg.sender, playPrice * 2);
Ok, agree. +1 the proposed change. To evaluate =3 as in the previous comment.

2023-04-04 10:40 UTC, 78carla commented on contracts/Casino.sol
> +    string public coin;
Yes. it is. I have added it only for testing the function. But can be removed. :-)

2023-04-04 11:39 UTC, merged